### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by PonteIneptique**
The #4 is something I am definitely not happy with, I see the need but the duplication in `@use` is problematic to me. Could the `discover` actually targets the identifier holder instead of the passage ?

I renamed elements for the moment because it seems easier to read. If we end up using something else, I'll be ok with it.

### CODE REVIEW

**Comment by hcayless** [comment]
I'd really like to be able to see yours and mine side-by-side. Could you label yours "Proposal 2" vel sim. and add it to the document instead of replacing the initial proposal?

**Comment by PonteIneptique** [comment]
Sure. I just like diff too much sometime...

**Comment by PonteIneptique** [comment]
Here you go : https://github.com/distributed-text-services/tei-proposal/blob/PonteIneptique-patch-1/Proposal%20Alternative.md

**Comment by PonteIneptique** [comment]
Wrong link and branch : https://github.com/distributed-text-services/tei-proposal/blob/master/AlternativeProposal.md

**Pull request closed without merging**
